name: auth-service

networks:
  auth-service:
    name: auth-service
    driver: bridge

services:
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    volumes:
      - ./src/:/app/src/
      - ./main.py:/app/main.py

    depends_on:
      - auth-service-redis

    networks:
      - auth-service

    ports:
      - "${API_PORT}:${API_PORT}"

  auth-service-redis:
    image: redis:7-alpine
    container_name: auth-service-redis
    restart: no
    env_file:
      - .env

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - auth-service

  auth-service-redisinsight:
    image: redis/redisinsight:latest
    container_name: auth-service-redisinsight
    restart: no
    env_file:
      - .env

    ports:
      - "${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}"

    volumes:
      - ./.redisinsight:/data

    depends_on:
      auth-service-redis:
        condition: service_healthy

    networks:
      - auth-service
